### ISSUE TITLE
request for spark! resources - SCC file access

### ISSUE THREAD

**Issue by samzorps** [BU-Spark/ml-bpl-liberator#18]
Hi ian, 

We are possibly done with our model and the next step is to download the Liberator newspaper dataset to the SCC for our model to run on. This dataset is about 8,000 images. I believe a previous team may have already downloaded this data to the SCC at /restricted/projectnb/cs501t2 ([link to previous team's dataset](https://scc-ondemand2.bu.edu/pun/sys/files/fs/restricted/projectnb/cs501t2)). When I try to enter this directory it says I don't have access. Can you give me access to this directory? Also, could our model at /projectnb/sparkgrp/bpl-new ([link to our model's folder](https://scc-ondemand2.bu.edu/pun/sys/files/fs/projectnb/sparkgrp/bpl-new/)) read and use these files?

The final project is due next wednesday.

Thanks,
Sam

**Comment by samzorps** [comment]
Following up- is this possible? @IanSaucy

**Comment by IanSaucy** [comment]
Hey,

Unfortunately these are from a class and are no longer accessible/exist. You will need to re-download them.

**Comment by samzorps** [comment]
Ah, I see. Thanks for your help!
