### ISSUE TITLE
 Request for Spark! Tech Resources for ml-bpl-liberator - encrypted secrets 

### ISSUE THREAD

**Issue by samzorps** [BU-Spark/ml-bpl-liberator#5]
I (sam zorpette, zorpette@bu.edu) need to add encrypted secrets to this repository to allow our github actions automated testing to run. We use google vision API and need to add the key to the encrypted secrets to allow github actions to access it securely. I need admin access to the repo to add an encrypted secret. If this is impossible maybe you can add the secret. This assignment was due last friday. 

Thanks!

**Comment by IanSaucy** [comment]
You should have access now!
