### ISSUE TITLE
Request for Spark! Tech Resources for ml-bpl-liberator - Spark Google cloud platform credentials 

### ISSUE THREAD

**Issue by samzorps** [BU-Spark/ml-bpl-liberator#7]
As part of our pipeline we utilize Google Cloud Vision for OCR. Accessing the Google CV API requires setting up a service account and downloading a credentials.json file which contains the API Keys needed. This credentials.json file can be downloaded from google with instructions [here](https://cloud.google.com/docs/authentication/getting-started#creating_a_service_account). This is the environment secret I need to add to github for our pipeline to run. I was wondering if we have a Spark! Google cloud account that I can use for this project. If so can you please send me the credentials.json?

Thanks again!

**Comment by IanSaucy** [comment]
Please include any deadlines

**Comment by samzorps** [comment]
This project was due already, so whenever you are able. I want to use the organization's google cloud credentials because I have to upload them to this spark! repo as an environment secret.

**Comment by IanSaucy** [comment]
Sam,

I've created a project on GCP and added you as an owner. You can use this to create the required credentials etc. Please document exactly what you do for future teams. 

https://console.cloud.google.com/home/dashboard?project=ml-bpl-liberator&organizationId=935399055473

Thanks,
Ian

**Comment by samzorps** [comment]
Great, this should work. 
Thanks so much!
